# Emit the pruned Fineract schema.
#
# Input:  a pg_dump --schema-only of the full Liquibase-built database.
# -v KEEPFILE=<file>: one table name per line, the set to retain.
# Output: SQL on stdout; a counts summary on stderr.
#
# Statements are accumulated until a line ends with ';', then classified.
# Emission order matters: tables, identity columns, PK/UNIQUE, indexes, then
# foreign keys last so the order tables were created in is irrelevant.
#
# Parsing is index/substr based rather than regex based wherever a match would
# have to span a newline: awk implementations disagree on whether "." matches
# a newline, and a silent mismatch here produces an empty migration.

BEGIN {
    while ((getline t < KEEPFILE) > 0) {
        sub(/\r$/, "", t)
        if (t != "") keep[t] = 1
    }
    close(KEEPFILE)
}

function firstline(s,   p) {
    p = index(s, "\n")
    return (p ? substr(s, 1, p - 1) : s)
}

# Strip a leading prefix, then everything from the first delimiter onward,
# leaving a bare table name.
function tblafter(s, pat,   n) {
    n = s
    sub(pat, "", n)
    sub(/[ (;,].*$/, "", n)
    return n
}

# The table named by "REFERENCES public.<table>(...)".
function reftarget(s,   p, r, q) {
    p = index(s, "REFERENCES public.")
    if (p == 0) return ""
    r = substr(s, p + 18)          # length("REFERENCES public.") == 18
    q = index(r, "(")
    if (q) r = substr(r, 1, q - 1)
    gsub(/[ \t\r\n;]/, "", r)
    return r
}

{
    # The dump arrives with CRLF endings if it was checked out on Windows; the
    # ";" terminator test below fails silently against a trailing return.
    sub(/\r$/, "")

    # pg_dump precedes every object with a "--" banner and a blank line. Those
    # lines do not end in ';', so without this they accumulate into the buffer
    # and every statement appears to start with "--" rather than its keyword.
    if (buf == "" && ($0 ~ /^--/ || $0 ~ /^[ \t]*$/)) next

    buf = buf $0 "\n"
    if ($0 !~ /;[ \t]*$/) next

    stmt = buf
    buf = ""
    first = firstline(stmt)

    if (first ~ /^CREATE TABLE public\./) {
        t = tblafter(first, "^CREATE TABLE public\\.")
        if (t in keep) { tables[++nt] = stmt; n_table++ }
    }
    else if (first ~ /^ALTER TABLE public\..* ALTER COLUMN /) {
        t = tblafter(first, "^ALTER TABLE public\\.")
        if (t in keep) { ident[++ni] = stmt; n_ident++ }
    }
    else if (first ~ /^ALTER TABLE ONLY public\./) {
        t = tblafter(first, "^ALTER TABLE ONLY public\\.")
        if (t in keep) {
            if (stmt ~ /FOREIGN KEY/) {
                # By construction of the closure the target is always in the
                # set. The guard exists so that a FK pointing outside it is
                # dropped rather than producing a migration that cannot apply.
                if (reftarget(stmt) in keep) { fks[++nf] = stmt; n_fk++ }
                else { n_fk_dropped++ }
            } else {
                cons[++nc] = stmt; n_cons++
            }
        }
    }
    else if (first ~ /^CREATE (UNIQUE )?INDEX /) {
        t = tblafter(first, "^CREATE (UNIQUE )?INDEX [^ ]+ ON public\\.")
        if (t in keep) { idx[++nx] = stmt; n_idx++ }
    }
}

END {
    print "-- Fineract core banking schema, pruned to the tables the query agent needs."
    print "--"
    print "-- Generated by scripts/stage1/prune-schema.sh from a pg_dump of a real"
    print "-- Liquibase run (scripts/stage1/dump-fineract-schema.sh). Do not hand-edit:"
    print "-- regenerate instead. See docs/DOMAIN.md section 1.2 for why the schema is"
    print "-- taken from a live migration rather than transcribed from changelog XML."
    print "--"
    print "-- Table set: the 18 in-scope tables from docs/DOMAIN.md section 2, plus the"
    print "-- transitive closure of their foreign keys. Column names are those of"
    print "-- Fineract, verbatim (decision 3)."
    print ""

    for (i = 1; i <= nt; i++) print tables[i]
    for (i = 1; i <= ni; i++) print ident[i]
    for (i = 1; i <= nc; i++) print cons[i]
    for (i = 1; i <= nx; i++) print idx[i]
    for (i = 1; i <= nf; i++) print fks[i]

    printf("-- tables=%d identity=%d constraints=%d indexes=%d fks=%d fks_dropped=%d\n",
           n_table, n_ident, n_cons, n_idx, n_fk, n_fk_dropped) > "/dev/stderr"
}
