-- Fineract core banking schema, pruned to the tables the query agent needs.
--
-- Generated by scripts/stage1/prune-schema.sh from a pg_dump of a real
-- Liquibase run (scripts/stage1/dump-fineract-schema.sh). Do not hand-edit:
-- regenerate instead. See docs/DOMAIN.md section 1.2 for why the schema is
-- taken from a live migration rather than transcribed from changelog XML.
--
-- Table set: the 18 in-scope tables from docs/DOMAIN.md section 2, plus the
-- transitive closure of their foreign keys. Column names are those of
-- Fineract, verbatim (decision 3).

CREATE TABLE public.acc_gl_account (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    parent_id bigint,
    hierarchy character varying(50),
    gl_code character varying(45) NOT NULL,
    disabled boolean DEFAULT false NOT NULL,
    manual_journal_entries_allowed boolean DEFAULT true NOT NULL,
    account_usage smallint DEFAULT 2 NOT NULL,
    classification_enum smallint NOT NULL,
    tag_id integer,
    description character varying(500)
);

CREATE TABLE public.glim_accounts (
    id bigint NOT NULL,
    group_id bigint DEFAULT 0 NOT NULL,
    account_number character varying(50) NOT NULL,
    principal_amount numeric(19,6) DEFAULT 0 NOT NULL,
    child_accounts_count integer NOT NULL,
    accepting_child boolean DEFAULT false NOT NULL,
    loan_status_id smallint DEFAULT 0 NOT NULL,
    application_id numeric(10,0) DEFAULT 0
);

CREATE TABLE public.gsim_accounts (
    id bigint NOT NULL,
    group_id bigint DEFAULT 0 NOT NULL,
    account_number character varying(50) NOT NULL,
    parent_deposit numeric(19,6) DEFAULT 0 NOT NULL,
    child_accounts_count integer NOT NULL,
    accepting_child boolean DEFAULT false NOT NULL,
    savings_status_id smallint DEFAULT 0 NOT NULL,
    application_id numeric(10,0) DEFAULT 0
);

CREATE TABLE public.m_appuser (
    id bigint NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    office_id bigint,
    staff_id bigint,
    username character varying(100) NOT NULL,
    firstname character varying(100) NOT NULL,
    lastname character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    email character varying(254) NOT NULL,
    firsttime_login_remaining boolean NOT NULL,
    nonexpired boolean NOT NULL,
    nonlocked boolean NOT NULL,
    nonexpired_credentials boolean NOT NULL,
    enabled boolean NOT NULL,
    last_time_password_updated date DEFAULT '1970-01-01'::date NOT NULL,
    password_never_expires boolean DEFAULT false NOT NULL,
    cannot_change_password boolean DEFAULT false,
    password_reset_required boolean DEFAULT false NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    is_login_retries_enabled boolean DEFAULT false NOT NULL,
    temporary_password character varying(255),
    temporary_password_expiry_time timestamp with time zone,
    is_password_reset_enabled boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_charge (
    id bigint NOT NULL,
    name character varying(100),
    currency_code character varying(3) NOT NULL,
    charge_applies_to_enum smallint NOT NULL,
    charge_time_enum smallint NOT NULL,
    charge_calculation_enum smallint NOT NULL,
    charge_payment_mode_enum smallint,
    amount numeric(19,6) NOT NULL,
    fee_on_day smallint,
    fee_interval smallint,
    fee_on_month smallint,
    is_penalty boolean DEFAULT false NOT NULL,
    is_active boolean NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL,
    min_cap numeric(19,6) DEFAULT NULL::numeric,
    max_cap numeric(19,6) DEFAULT NULL::numeric,
    fee_frequency smallint,
    is_free_withdrawal boolean DEFAULT false NOT NULL,
    free_withdrawal_charge_frequency integer DEFAULT 0,
    restart_frequency integer DEFAULT 0,
    restart_frequency_enum integer DEFAULT 0,
    is_payment_type boolean DEFAULT false,
    payment_type_id integer,
    income_or_liability_account_id bigint,
    tax_group_id bigint
);

CREATE TABLE public.m_client (
    id bigint NOT NULL,
    account_no character varying(20) NOT NULL,
    external_id character varying(100),
    status_enum integer DEFAULT 300 NOT NULL,
    sub_status integer,
    activation_date date,
    office_joining_date date,
    office_id bigint NOT NULL,
    transfer_to_office_id bigint,
    staff_id bigint,
    firstname character varying(50),
    middlename character varying(50),
    lastname character varying(50),
    fullname character varying(160),
    display_name character varying(160) NOT NULL,
    mobile_no character varying(50),
    is_staff boolean DEFAULT false NOT NULL,
    gender_cv_id integer,
    date_of_birth date,
    image_id bigint,
    closure_reason_cv_id integer,
    closedon_date date,
    updated_by bigint,
    updated_on date,
    submittedon_date date,
    activatedon_userid bigint,
    closedon_userid bigint,
    default_savings_product bigint,
    default_savings_account bigint,
    client_type_cv_id integer,
    client_classification_cv_id integer,
    reject_reason_cv_id integer,
    rejectedon_date date,
    rejectedon_userid bigint,
    withdraw_reason_cv_id integer,
    withdrawn_on_date date,
    withdraw_on_userid bigint,
    reactivated_on_date date,
    reactivated_on_userid bigint,
    legal_form_enum integer,
    reopened_on_date date,
    reopened_by_userid bigint,
    email_address character varying(254),
    proposed_transfer_date date,
    created_on_utc timestamp with time zone NOT NULL,
    created_by bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL
);

CREATE TABLE public.m_code (
    id integer NOT NULL,
    code_name character varying(100),
    is_system_defined boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_code_value (
    id integer NOT NULL,
    code_id integer NOT NULL,
    code_value character varying(100),
    code_description character varying(500),
    order_position integer DEFAULT 0 NOT NULL,
    code_score integer,
    is_active boolean DEFAULT true NOT NULL,
    is_mandatory boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_currency (
    id bigint NOT NULL,
    code character varying(3) NOT NULL,
    decimal_places smallint NOT NULL,
    currency_multiplesof smallint,
    display_symbol character varying(10),
    name character varying(50) NOT NULL,
    internationalized_name_code character varying(50) NOT NULL
);

CREATE TABLE public.m_delinquency_bucket (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    created_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    version bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    bucket_type character varying(50) DEFAULT 'REGULAR'::character varying NOT NULL
);

CREATE TABLE public.m_delinquency_bucket_mappings (
    id bigint NOT NULL,
    delinquency_range_id bigint NOT NULL,
    delinquency_bucket_id bigint NOT NULL,
    created_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    version bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL
);

CREATE TABLE public.m_delinquency_range (
    id bigint NOT NULL,
    classification character varying(100) NOT NULL,
    min_age_days bigint NOT NULL,
    max_age_days bigint,
    created_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    version bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL
);

CREATE TABLE public.m_fund (
    id bigint NOT NULL,
    name character varying(255),
    external_id character varying(100)
);

CREATE TABLE public.m_group (
    id bigint NOT NULL,
    external_id character varying(100),
    status_enum integer DEFAULT 300 NOT NULL,
    activation_date date,
    office_id bigint NOT NULL,
    staff_id bigint,
    parent_id bigint,
    level_id integer NOT NULL,
    display_name character varying(100) NOT NULL,
    hierarchy character varying(100),
    closure_reason_cv_id integer,
    closedon_date date,
    activatedon_userid bigint,
    submittedon_date date,
    submittedon_userid bigint,
    closedon_userid bigint,
    account_no character varying(20) NOT NULL
);

CREATE TABLE public.m_group_level (
    id integer CONSTRAINT m_group_level_id_not_null1 NOT NULL,
    parent_id integer,
    super_parent boolean NOT NULL,
    level_name character varying(100) NOT NULL,
    recursable boolean NOT NULL,
    can_have_clients boolean NOT NULL
);

CREATE TABLE public.m_image (
    id bigint NOT NULL,
    location character varying(500),
    storage_type_enum smallint
);

CREATE TABLE public.m_loan (
    id bigint NOT NULL,
    account_no character varying(20) NOT NULL,
    external_id character varying(100),
    client_id bigint,
    group_id bigint,
    glim_id bigint,
    product_id bigint,
    fund_id bigint,
    loan_officer_id bigint,
    loanpurpose_cv_id integer,
    loan_status_id smallint NOT NULL,
    loan_type_enum smallint NOT NULL,
    currency_code character varying(3) NOT NULL,
    currency_digits smallint NOT NULL,
    currency_multiplesof smallint,
    principal_amount_proposed numeric(19,6) NOT NULL,
    principal_amount numeric(19,6) NOT NULL,
    approved_principal numeric(19,6) NOT NULL,
    net_disbursal_amount numeric(19,6) NOT NULL,
    arrearstolerance_amount numeric(19,6) DEFAULT NULL::numeric,
    is_floating_interest_rate boolean DEFAULT false,
    interest_rate_differential numeric(19,6) DEFAULT 0,
    nominal_interest_rate_per_period numeric(19,6) DEFAULT NULL::numeric,
    interest_period_frequency_enum smallint,
    annual_nominal_interest_rate numeric(19,6) DEFAULT NULL::numeric,
    interest_method_enum smallint NOT NULL,
    interest_calculated_in_period_enum smallint DEFAULT 1 NOT NULL,
    allow_partial_period_interest_calcualtion boolean DEFAULT false NOT NULL,
    term_frequency smallint DEFAULT 0 NOT NULL,
    term_period_frequency_enum smallint DEFAULT 2 NOT NULL,
    repay_every smallint NOT NULL,
    repayment_period_frequency_enum smallint NOT NULL,
    number_of_repayments smallint NOT NULL,
    grace_on_principal_periods smallint,
    recurring_moratorium_principal_periods smallint,
    grace_on_interest_periods smallint,
    grace_interest_free_periods smallint,
    amortization_method_enum smallint NOT NULL,
    submittedon_date date,
    approvedon_date date,
    approvedon_userid bigint,
    expected_disbursedon_date date,
    expected_firstrepaymenton_date date,
    interest_calculated_from_date date,
    disbursedon_date date,
    disbursedon_userid bigint,
    expected_maturedon_date date,
    maturedon_date date,
    closedon_date date,
    closedon_userid bigint,
    total_charges_due_at_disbursement_derived numeric(19,6) DEFAULT NULL::numeric,
    principal_disbursed_derived numeric(19,6) DEFAULT 0 NOT NULL,
    principal_repaid_derived numeric(19,6) DEFAULT 0 NOT NULL,
    principal_writtenoff_derived numeric(19,6) DEFAULT 0 NOT NULL,
    principal_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_charged_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_repaid_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_waived_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_writtenoff_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_charged_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_repaid_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_waived_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_writtenoff_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_charged_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_repaid_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_waived_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_writtenoff_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_expected_repayment_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_repayment_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_expected_costofloan_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_costofloan_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_waived_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_writtenoff_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_overpaid_derived numeric(19,6) DEFAULT NULL::numeric,
    rejectedon_date date,
    rejectedon_userid bigint,
    rescheduledon_date date,
    rescheduledon_userid bigint,
    withdrawnon_date date,
    withdrawnon_userid bigint,
    writtenoffon_date date,
    loan_transaction_strategy_id bigint,
    sync_disbursement_with_meeting boolean,
    loan_counter smallint,
    loan_product_counter smallint,
    fixed_emi_amount numeric(19,6) DEFAULT NULL::numeric,
    max_outstanding_loan_balance numeric(19,6) DEFAULT NULL::numeric,
    grace_on_arrears_ageing smallint,
    is_npa boolean DEFAULT false NOT NULL,
    total_recovered_derived numeric(19,6) DEFAULT NULL::numeric,
    accrued_till date,
    interest_recalcualated_on date,
    days_in_month_enum smallint DEFAULT 1 NOT NULL,
    days_in_year_enum smallint DEFAULT 1 NOT NULL,
    interest_recalculation_enabled boolean DEFAULT false NOT NULL,
    guarantee_amount_derived numeric(19,6) DEFAULT NULL::numeric,
    create_standing_instruction_at_disbursement boolean,
    version integer DEFAULT 1 NOT NULL,
    writeoff_reason_cv_id integer,
    loan_sub_status_id smallint,
    is_topup boolean DEFAULT false NOT NULL,
    is_equal_amortization boolean DEFAULT false NOT NULL,
    fixed_principal_percentage_per_installment numeric(5,2) DEFAULT NULL::numeric,
    created_on_utc timestamp with time zone NOT NULL,
    created_by bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    principal_adjustments_derived numeric(19,6) DEFAULT 0 NOT NULL,
    is_fraud boolean DEFAULT false NOT NULL,
    loan_transaction_strategy_code character varying(100) DEFAULT '-'::character varying NOT NULL,
    loan_transaction_strategy_name character varying(100) DEFAULT '-'::character varying NOT NULL,
    last_closed_business_date date,
    overpaidon_date date,
    is_charged_off boolean DEFAULT false NOT NULL,
    charged_off_on_date date,
    charge_off_reason_cv_id bigint,
    charged_off_by_userid bigint,
    enable_down_payment boolean DEFAULT false NOT NULL,
    disbursed_amount_percentage_for_down_payment numeric(9,6) DEFAULT NULL::numeric,
    enable_installment_level_delinquency boolean DEFAULT false NOT NULL,
    enable_accrual_activity_posting boolean DEFAULT false NOT NULL,
    days_in_year_custom_strategy character varying(100),
    enable_income_capitalization boolean DEFAULT false NOT NULL,
    capitalized_income_calculation_type character varying(100),
    capitalized_income_strategy character varying(100),
    capitalized_income_type character varying(10),
    capitalized_income_derived numeric(19,6) DEFAULT 0 NOT NULL,
    capitalized_income_adjustment_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_principal_derived numeric(19,6) DEFAULT 0 NOT NULL,
    enable_buy_down_fee boolean DEFAULT false NOT NULL,
    buy_down_fee_calculation_type character varying(100),
    buy_down_fee_strategy character varying(100),
    buy_down_fee_income_type character varying(100),
    allow_full_term_for_tranche boolean DEFAULT false NOT NULL,
    repayment_start_date_type_enum smallint,
    enable_auto_repayment_for_down_payment boolean DEFAULT false NOT NULL,
    loan_schedule_type character varying(20) DEFAULT 'CUMULATIVE'::character varying NOT NULL,
    loan_schedule_processing_type character varying(20) DEFAULT 'HORIZONTAL'::character varying NOT NULL,
    fee_adjustments_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_adjustments_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fixed_length smallint,
    supported_interest_refund_types text,
    charge_off_behaviour character varying(20) DEFAULT 'REGULAR'::character varying,
    interest_recognition_on_disbursement_date boolean DEFAULT false NOT NULL,
    installment_amount_in_multiples_of numeric(19,6) DEFAULT NULL::numeric,
    is_merchant_buy_down_fee boolean DEFAULT true NOT NULL
);

CREATE TABLE public.m_loan_arrears_aging (
    loan_id bigint NOT NULL,
    principal_overdue_derived numeric(19,6) DEFAULT 0 NOT NULL,
    interest_overdue_derived numeric(19,6) DEFAULT 0 NOT NULL,
    fee_charges_overdue_derived numeric(19,6) DEFAULT 0 NOT NULL,
    penalty_charges_overdue_derived numeric(19,6) DEFAULT 0 NOT NULL,
    total_overdue_derived numeric(19,6) DEFAULT 0 NOT NULL,
    overdue_since_date_derived date
);

CREATE TABLE public.m_loan_charge (
    id bigint NOT NULL,
    loan_id bigint NOT NULL,
    charge_id bigint NOT NULL,
    is_penalty boolean DEFAULT false NOT NULL,
    charge_time_enum smallint NOT NULL,
    due_for_collection_as_of_date date,
    charge_calculation_enum smallint NOT NULL,
    charge_payment_mode_enum smallint DEFAULT 0 NOT NULL,
    calculation_percentage numeric(19,6) DEFAULT NULL::numeric,
    calculation_on_amount numeric(19,6) DEFAULT NULL::numeric,
    charge_amount_or_percentage numeric(19,6) DEFAULT NULL::numeric,
    amount numeric(19,6) NOT NULL,
    amount_paid_derived numeric(19,6) DEFAULT NULL::numeric,
    amount_waived_derived numeric(19,6) DEFAULT NULL::numeric,
    amount_writtenoff_derived numeric(19,6) DEFAULT NULL::numeric,
    amount_outstanding_derived numeric(19,6) DEFAULT 0 NOT NULL,
    is_paid_derived boolean DEFAULT false NOT NULL,
    waived boolean DEFAULT false NOT NULL,
    min_cap numeric(19,6) DEFAULT NULL::numeric,
    max_cap numeric(19,6) DEFAULT NULL::numeric,
    is_active boolean DEFAULT true NOT NULL,
    external_id character varying(100),
    submitted_on_date date,
    created_on_utc timestamp with time zone NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    created_by bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    tax_amount numeric(19,6)
);

CREATE TABLE public.m_loan_delinquency_tag_history (
    id bigint NOT NULL,
    delinquency_range_id bigint NOT NULL,
    loan_id bigint NOT NULL,
    addedon_date date NOT NULL,
    liftedon_date date,
    created_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    version bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL
);

CREATE TABLE public.m_loan_repayment_schedule (
    id bigint NOT NULL,
    loan_id bigint NOT NULL,
    fromdate date,
    duedate date NOT NULL,
    installment smallint NOT NULL,
    principal_amount numeric(19,6) DEFAULT NULL::numeric,
    principal_completed_derived numeric(19,6) DEFAULT NULL::numeric,
    principal_writtenoff_derived numeric(19,6) DEFAULT NULL::numeric,
    interest_amount numeric(19,6) DEFAULT NULL::numeric,
    interest_completed_derived numeric(19,6) DEFAULT NULL::numeric,
    interest_writtenoff_derived numeric(19,6) DEFAULT NULL::numeric,
    interest_waived_derived numeric(19,6) DEFAULT NULL::numeric,
    accrual_interest_derived numeric(19,6) DEFAULT NULL::numeric,
    reschedule_interest_portion numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_amount numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_completed_derived numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_writtenoff_derived numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_waived_derived numeric(19,6) DEFAULT NULL::numeric,
    accrual_fee_charges_derived numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_amount numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_completed_derived numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_writtenoff_derived numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_waived_derived numeric(19,6) DEFAULT NULL::numeric,
    accrual_penalty_charges_derived numeric(19,6) DEFAULT NULL::numeric,
    total_paid_in_advance_derived numeric(19,6) DEFAULT NULL::numeric,
    total_paid_late_derived numeric(19,6) DEFAULT NULL::numeric,
    completed_derived boolean NOT NULL,
    obligations_met_on_date date,
    created_by bigint NOT NULL,
    created_date timestamp without time zone,
    lastmodified_date timestamp without time zone,
    last_modified_by bigint NOT NULL,
    recalculated_interest_component boolean DEFAULT false CONSTRAINT m_loan_repayment_schedule_recalculated_interest_compon_not_null NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    is_additional boolean DEFAULT false NOT NULL,
    credits_amount numeric(19,6) DEFAULT NULL::numeric,
    is_down_payment boolean DEFAULT false NOT NULL,
    credited_interest numeric(19,6),
    credited_fee numeric(19,6) DEFAULT NULL::numeric,
    credited_penalty numeric(19,6) DEFAULT NULL::numeric,
    is_re_aged boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_loan_transaction (
    id bigint NOT NULL,
    loan_id bigint NOT NULL,
    office_id bigint NOT NULL,
    payment_detail_id bigint,
    is_reversed boolean NOT NULL,
    external_id character varying(100),
    transaction_type_enum smallint NOT NULL,
    transaction_date date NOT NULL,
    amount numeric(19,6) NOT NULL,
    principal_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    interest_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    overpayment_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    unrecognized_income_portion numeric(19,6) DEFAULT NULL::numeric,
    outstanding_loan_balance_derived numeric(19,6) DEFAULT NULL::numeric,
    submitted_on_date date NOT NULL,
    manually_adjusted_or_reversed boolean DEFAULT false,
    created_date timestamp without time zone,
    created_by bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    charge_refund_charge_type character varying(1),
    reversal_external_id character varying(100) DEFAULT NULL::character varying,
    reversed_on_date date,
    version bigint DEFAULT 1 NOT NULL,
    classification_cv_id bigint
);

CREATE TABLE public.m_loan_transaction_repayment_schedule_mapping (
    id bigint NOT NULL,
    loan_transaction_id bigint CONSTRAINT m_loan_transaction_repayment_sched_loan_transaction_id_not_null NOT NULL,
    loan_repayment_schedule_id bigint CONSTRAINT m_loan_transaction_repaymen_loan_repayment_schedule_id_not_null NOT NULL,
    amount numeric(19,6) NOT NULL,
    principal_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    interest_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    fee_charges_portion_derived numeric(19,6) DEFAULT NULL::numeric,
    penalty_charges_portion_derived numeric(19,6) DEFAULT NULL::numeric
);

CREATE TABLE public.m_office (
    id bigint NOT NULL,
    parent_id bigint,
    hierarchy character varying(100),
    external_id character varying(100),
    name character varying(50) NOT NULL,
    opening_date date NOT NULL
);

CREATE TABLE public.m_payment_detail (
    id bigint NOT NULL,
    payment_type_id integer,
    account_number character varying(100),
    check_number character varying(100),
    receipt_number character varying(100),
    bank_number character varying(100),
    routing_code character varying(100)
);

CREATE TABLE public.m_payment_type (
    id integer NOT NULL,
    value character varying(100),
    description character varying(500),
    is_cash_payment boolean DEFAULT false,
    order_position integer DEFAULT 0 NOT NULL,
    code_name character varying(100),
    is_system_defined boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_product_loan (
    id bigint NOT NULL,
    short_name character varying(4) NOT NULL,
    currency_code character varying(3) NOT NULL,
    currency_digits smallint NOT NULL,
    currency_multiplesof smallint,
    principal_amount numeric(19,6) DEFAULT NULL::numeric,
    min_principal_amount numeric(19,6) DEFAULT NULL::numeric,
    max_principal_amount numeric(19,6) DEFAULT NULL::numeric,
    arrearstolerance_amount numeric(19,6) DEFAULT NULL::numeric,
    name character varying(100) NOT NULL,
    description character varying(500),
    fund_id bigint,
    is_linked_to_floating_interest_rates boolean DEFAULT false NOT NULL,
    allow_variabe_installments boolean DEFAULT false NOT NULL,
    nominal_interest_rate_per_period numeric(19,6) DEFAULT NULL::numeric,
    min_nominal_interest_rate_per_period numeric(19,6) DEFAULT NULL::numeric,
    max_nominal_interest_rate_per_period numeric(19,6) DEFAULT NULL::numeric,
    interest_period_frequency_enum smallint,
    annual_nominal_interest_rate numeric(19,6) DEFAULT NULL::numeric,
    interest_method_enum smallint NOT NULL,
    interest_calculated_in_period_enum smallint DEFAULT 1 NOT NULL,
    allow_partial_period_interest_calcualtion boolean DEFAULT false CONSTRAINT m_product_loan_allow_partial_period_interest_calcualti_not_null NOT NULL,
    repay_every smallint NOT NULL,
    repayment_period_frequency_enum smallint NOT NULL,
    number_of_repayments smallint NOT NULL,
    min_number_of_repayments smallint,
    max_number_of_repayments smallint,
    grace_on_principal_periods smallint,
    recurring_moratorium_principal_periods smallint,
    grace_on_interest_periods smallint,
    grace_interest_free_periods smallint,
    amortization_method_enum smallint NOT NULL,
    accounting_type smallint NOT NULL,
    loan_transaction_strategy_id bigint,
    external_id character varying(100),
    include_in_borrower_cycle boolean DEFAULT false NOT NULL,
    use_borrower_cycle boolean DEFAULT false NOT NULL,
    start_date date,
    close_date date,
    allow_multiple_disbursals boolean DEFAULT false NOT NULL,
    max_disbursals integer,
    max_outstanding_loan_balance numeric(19,6) DEFAULT NULL::numeric,
    grace_on_arrears_ageing smallint,
    overdue_days_for_npa smallint,
    days_in_month_enum smallint DEFAULT 1 NOT NULL,
    days_in_year_enum smallint DEFAULT 1 NOT NULL,
    interest_recalculation_enabled boolean DEFAULT false NOT NULL,
    min_days_between_disbursal_and_first_repayment integer,
    hold_guarantee_funds boolean DEFAULT false NOT NULL,
    principal_threshold_for_last_installment numeric(5,2) DEFAULT 50 CONSTRAINT m_product_loan_principal_threshold_for_last_installmen_not_null NOT NULL,
    account_moves_out_of_npa_only_on_arrears_completion boolean DEFAULT false CONSTRAINT m_product_loan_account_moves_out_of_npa_only_on_arrear_not_null NOT NULL,
    can_define_fixed_emi_amount boolean DEFAULT false NOT NULL,
    installment_amount_in_multiples_of numeric(19,6) DEFAULT NULL::numeric,
    can_use_for_topup boolean DEFAULT false NOT NULL,
    sync_expected_with_disbursement_date boolean DEFAULT false,
    is_equal_amortization boolean DEFAULT false NOT NULL,
    fixed_principal_percentage_per_installment numeric(5,2) DEFAULT NULL::numeric,
    disallow_expected_disbursements boolean DEFAULT false NOT NULL,
    allow_approved_disbursed_amounts_over_applied boolean DEFAULT false CONSTRAINT m_product_loan_allow_approved_disbursed_amounts_over_a_not_null NOT NULL,
    over_applied_calculation_type character varying(10),
    over_applied_number integer,
    delinquency_bucket_id bigint,
    loan_transaction_strategy_code character varying(100) DEFAULT '-'::character varying NOT NULL,
    loan_transaction_strategy_name character varying(100) DEFAULT '-'::character varying NOT NULL,
    due_days_for_repayment_event integer,
    overdue_days_for_repayment_event integer,
    enable_down_payment boolean DEFAULT false NOT NULL,
    disbursed_amount_percentage_for_down_payment numeric(9,6) DEFAULT NULL::numeric,
    enable_installment_level_delinquency boolean DEFAULT false NOT NULL,
    enable_accrual_activity_posting boolean DEFAULT false NOT NULL,
    days_in_year_custom_strategy character varying(100),
    enable_income_capitalization boolean DEFAULT false NOT NULL,
    capitalized_income_calculation_type character varying(100),
    capitalized_income_strategy character varying(100),
    capitalized_income_type character varying(10),
    enable_buy_down_fee boolean DEFAULT false NOT NULL,
    buy_down_fee_calculation_type character varying(100),
    buy_down_fee_strategy character varying(100),
    buy_down_fee_income_type character varying(100),
    allow_full_term_for_tranche boolean DEFAULT false NOT NULL,
    enable_auto_repayment_for_down_payment boolean DEFAULT false NOT NULL,
    repayment_start_date_type_enum smallint DEFAULT 1 NOT NULL,
    loan_schedule_type character varying(20) DEFAULT 'CUMULATIVE'::character varying NOT NULL,
    loan_schedule_processing_type character varying(20) DEFAULT 'HORIZONTAL'::character varying NOT NULL,
    fixed_length smallint,
    supported_interest_refund_types text,
    charge_off_behaviour character varying(20) DEFAULT 'REGULAR'::character varying,
    interest_recognition_on_disbursement_date boolean DEFAULT false CONSTRAINT m_product_loan_interest_recognition_on_disbursement_da_not_null NOT NULL,
    is_merchant_buy_down_fee boolean DEFAULT true NOT NULL
);

CREATE TABLE public.m_savings_account (
    id bigint NOT NULL,
    account_no character varying(20) NOT NULL,
    external_id character varying(100),
    client_id bigint,
    group_id bigint,
    gsim_id bigint,
    product_id bigint,
    field_officer_id bigint,
    status_enum smallint DEFAULT 300 NOT NULL,
    sub_status_enum smallint DEFAULT 0 NOT NULL,
    account_type_enum smallint DEFAULT 1 NOT NULL,
    deposit_type_enum smallint DEFAULT 100 NOT NULL,
    submittedon_date date NOT NULL,
    submittedon_userid bigint,
    approvedon_date date,
    approvedon_userid bigint,
    rejectedon_date date,
    rejectedon_userid bigint,
    withdrawnon_date date,
    withdrawnon_userid bigint,
    activatedon_date date,
    activatedon_userid bigint,
    closedon_date date,
    closedon_userid bigint,
    currency_code character varying(3) NOT NULL,
    currency_digits smallint NOT NULL,
    currency_multiplesof smallint,
    nominal_annual_interest_rate numeric(19,6) NOT NULL,
    interest_compounding_period_enum smallint NOT NULL,
    interest_posting_period_enum smallint DEFAULT 4 NOT NULL,
    interest_calculation_type_enum smallint NOT NULL,
    interest_calculation_days_in_year_type_enum smallint CONSTRAINT m_savings_account_interest_calculation_days_in_year_ty_not_null NOT NULL,
    min_required_opening_balance numeric(19,6) DEFAULT NULL::numeric,
    lockin_period_frequency numeric(19,6) DEFAULT NULL::numeric,
    lockin_period_frequency_enum smallint,
    withdrawal_fee_for_transfer boolean DEFAULT true,
    allow_overdraft boolean DEFAULT false NOT NULL,
    overdraft_limit numeric(19,6) DEFAULT NULL::numeric,
    nominal_annual_interest_rate_overdraft numeric(19,6) DEFAULT 0,
    min_overdraft_for_interest_calculation numeric(19,6) DEFAULT 0,
    lockedin_until_date_derived date,
    total_deposits_derived numeric(19,6) DEFAULT NULL::numeric,
    total_withdrawals_derived numeric(19,6) DEFAULT NULL::numeric,
    total_withdrawal_fees_derived numeric(19,6) DEFAULT NULL::numeric,
    total_fees_charge_derived numeric(19,6) DEFAULT NULL::numeric,
    total_penalty_charge_derived numeric(19,6) DEFAULT NULL::numeric,
    total_annual_fees_derived numeric(19,6) DEFAULT NULL::numeric,
    total_interest_earned_derived numeric(19,6) DEFAULT NULL::numeric,
    total_interest_posted_derived numeric(19,6) DEFAULT NULL::numeric,
    total_overdraft_interest_derived numeric(19,6) DEFAULT 0,
    total_withhold_tax_derived numeric(19,6) DEFAULT NULL::numeric,
    account_balance_derived numeric(19,6) DEFAULT 0 NOT NULL,
    min_required_balance numeric(19,6) DEFAULT NULL::numeric,
    enforce_min_required_balance boolean DEFAULT false NOT NULL,
    min_balance_for_interest_calculation numeric(19,6) DEFAULT NULL::numeric,
    start_interest_calculation_date date,
    on_hold_funds_derived numeric(19,6) DEFAULT NULL::numeric,
    version integer DEFAULT 1 NOT NULL,
    withhold_tax boolean DEFAULT false NOT NULL,
    tax_group_id bigint,
    last_interest_calculation_date date,
    total_savings_amount_on_hold numeric(19,6) DEFAULT NULL::numeric,
    interest_posted_till_date date,
    reason_for_block character varying(256),
    max_allowed_lien_limit numeric(19,6) DEFAULT NULL::numeric,
    is_lien_allowed boolean DEFAULT false NOT NULL,
    created_by bigint NOT NULL,
    last_modified_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    accrued_till_date date,
    last_closed_business_date date
);

CREATE TABLE public.m_savings_account_transaction (
    id bigint NOT NULL,
    savings_account_id bigint NOT NULL,
    office_id bigint NOT NULL,
    payment_detail_id bigint,
    transaction_type_enum smallint NOT NULL,
    is_reversed boolean NOT NULL,
    transaction_date date NOT NULL,
    amount numeric(19,6) NOT NULL,
    overdraft_amount_derived numeric(19,6) DEFAULT NULL::numeric,
    balance_end_date_derived date,
    balance_number_of_days_derived integer,
    running_balance_derived numeric(19,6) DEFAULT NULL::numeric,
    cumulative_balance_derived numeric(19,6) DEFAULT NULL::numeric,
    created_date timestamp without time zone,
    created_by bigint NOT NULL,
    is_manual boolean DEFAULT false,
    release_id_of_hold_amount bigint,
    is_loan_disbursement boolean,
    ref_no character varying(128),
    original_transaction_id bigint,
    is_reversal boolean DEFAULT false NOT NULL,
    reason_for_block character varying(256),
    is_lien_transaction boolean DEFAULT false NOT NULL,
    submitted_on_date date NOT NULL,
    last_modified_by bigint NOT NULL,
    created_on_utc timestamp with time zone NOT NULL,
    last_modified_on_utc timestamp with time zone NOT NULL,
    external_id character varying(100)
);

CREATE TABLE public.m_savings_product (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    short_name character varying(4) NOT NULL,
    description character varying(500),
    deposit_type_enum smallint DEFAULT 100 NOT NULL,
    currency_code character varying(3) NOT NULL,
    currency_digits smallint NOT NULL,
    currency_multiplesof smallint,
    nominal_annual_interest_rate numeric(19,6) NOT NULL,
    interest_compounding_period_enum smallint NOT NULL,
    interest_posting_period_enum smallint DEFAULT 4 NOT NULL,
    interest_calculation_type_enum smallint NOT NULL,
    interest_calculation_days_in_year_type_enum smallint CONSTRAINT m_savings_product_interest_calculation_days_in_year_ty_not_null NOT NULL,
    min_required_opening_balance numeric(19,6) DEFAULT NULL::numeric,
    lockin_period_frequency numeric(19,6) DEFAULT NULL::numeric,
    lockin_period_frequency_enum smallint,
    accounting_type smallint NOT NULL,
    withdrawal_fee_amount numeric(19,6) DEFAULT NULL::numeric,
    withdrawal_fee_type_enum smallint,
    withdrawal_fee_for_transfer boolean DEFAULT true,
    allow_overdraft boolean DEFAULT false NOT NULL,
    overdraft_limit numeric(19,6) DEFAULT NULL::numeric,
    nominal_annual_interest_rate_overdraft numeric(19,6) DEFAULT 0,
    min_overdraft_for_interest_calculation numeric(19,6) DEFAULT 0,
    min_required_balance numeric(19,6) DEFAULT NULL::numeric,
    enforce_min_required_balance boolean DEFAULT false NOT NULL,
    min_balance_for_interest_calculation numeric(19,6) DEFAULT NULL::numeric,
    withhold_tax boolean DEFAULT false NOT NULL,
    tax_group_id bigint,
    is_dormancy_tracking_active boolean,
    days_to_inactive integer,
    days_to_dormancy integer,
    days_to_escheat integer,
    max_allowed_lien_limit numeric(19,6) DEFAULT NULL::numeric,
    is_lien_allowed boolean DEFAULT false NOT NULL
);

CREATE TABLE public.m_staff (
    id bigint NOT NULL,
    is_loan_officer boolean DEFAULT false NOT NULL,
    office_id bigint,
    firstname character varying(50),
    lastname character varying(50),
    display_name character varying(102) NOT NULL,
    mobile_no character varying(50),
    external_id character varying(100),
    organisational_role_enum smallint,
    organisational_role_parent_staff_id bigint,
    is_active boolean DEFAULT true NOT NULL,
    joining_date date,
    image_id bigint,
    email_address character varying(254)
);

CREATE TABLE public.m_tax_group (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    createdby_id bigint NOT NULL,
    created_date timestamp without time zone NOT NULL,
    lastmodifiedby_id bigint NOT NULL,
    lastmodified_date timestamp without time zone NOT NULL
);

ALTER TABLE public.acc_gl_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.acc_gl_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.glim_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.glim_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.gsim_accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gsim_accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_appuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_appuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_charge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_charge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_client ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_client_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_code_value ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_code_value_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_currency ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_currency_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_delinquency_bucket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_delinquency_bucket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_delinquency_bucket_mappings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_delinquency_bucket_mappings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_delinquency_range ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_delinquency_range_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_fund ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_fund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_group_level ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_group_level_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_arrears_aging ALTER COLUMN loan_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_arrears_aging_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_charge ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_charge_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_delinquency_tag_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_delinquency_tag_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_repayment_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_repayment_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_loan_transaction_repayment_schedule_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_loan_transaction_repayment_schedule_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_office ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_office_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_payment_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_payment_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_payment_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_payment_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_product_loan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_product_loan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_savings_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_savings_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_savings_account_transaction ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_savings_account_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_savings_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_savings_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_staff ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_staff_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.m_tax_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.m_tax_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.acc_gl_account
    ADD CONSTRAINT acc_gl_account_gl_code_key UNIQUE (gl_code);

ALTER TABLE ONLY public.acc_gl_account
    ADD CONSTRAINT acc_gl_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_code_value
    ADD CONSTRAINT code_value UNIQUE (code_id, code_value);

ALTER TABLE ONLY public.glim_accounts
    ADD CONSTRAINT glim_accounts_account_number_key UNIQUE (account_number);

ALTER TABLE ONLY public.glim_accounts
    ADD CONSTRAINT glim_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.gsim_accounts
    ADD CONSTRAINT gsim_accounts_account_number_key UNIQUE (account_number);

ALTER TABLE ONLY public.gsim_accounts
    ADD CONSTRAINT gsim_accounts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_appuser
    ADD CONSTRAINT m_appuser_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_charge
    ADD CONSTRAINT m_charge_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_charge
    ADD CONSTRAINT m_charge_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT m_client_account_no_key UNIQUE (account_no);

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT m_client_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT m_client_mobile_no_key UNIQUE (mobile_no);

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT m_client_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_code
    ADD CONSTRAINT m_code_code_name_key UNIQUE (code_name);

ALTER TABLE ONLY public.m_code
    ADD CONSTRAINT m_code_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_code_value
    ADD CONSTRAINT m_code_value_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_currency
    ADD CONSTRAINT m_currency_code_key UNIQUE (code);

ALTER TABLE ONLY public.m_currency
    ADD CONSTRAINT m_currency_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_delinquency_bucket_mappings
    ADD CONSTRAINT m_delinquency_bucket_mappings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_delinquency_bucket
    ADD CONSTRAINT m_delinquency_bucket_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_delinquency_bucket
    ADD CONSTRAINT m_delinquency_bucket_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_delinquency_range
    ADD CONSTRAINT m_delinquency_range_classification_key UNIQUE (classification);

ALTER TABLE ONLY public.m_delinquency_range
    ADD CONSTRAINT m_delinquency_range_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_fund
    ADD CONSTRAINT m_fund_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_fund
    ADD CONSTRAINT m_fund_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_fund
    ADD CONSTRAINT m_fund_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT m_group_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_group_level
    ADD CONSTRAINT m_group_level_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT m_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_image
    ADD CONSTRAINT m_image_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT m_loan_account_no_key UNIQUE (account_no);

ALTER TABLE ONLY public.m_loan_arrears_aging
    ADD CONSTRAINT m_loan_arrears_aging_pkey PRIMARY KEY (loan_id);

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT m_loan_charge_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT m_loan_charge_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan_delinquency_tag_history
    ADD CONSTRAINT m_loan_delinquency_tag_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT m_loan_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT m_loan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan_repayment_schedule
    ADD CONSTRAINT m_loan_repayment_schedule_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT m_loan_transaction_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT m_loan_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_loan_transaction_repayment_schedule_mapping
    ADD CONSTRAINT m_loan_transaction_repayment_schedule_mapping_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_office
    ADD CONSTRAINT m_office_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_office
    ADD CONSTRAINT m_office_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_office
    ADD CONSTRAINT m_office_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_payment_detail
    ADD CONSTRAINT m_payment_detail_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_payment_type
    ADD CONSTRAINT m_payment_type_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT m_product_loan_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT m_product_loan_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT m_product_loan_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT m_product_loan_short_name_key UNIQUE (short_name);

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT m_savings_account_account_no_key UNIQUE (account_no);

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT m_savings_account_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT m_savings_account_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT m_savings_account_transaction_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_savings_product
    ADD CONSTRAINT m_savings_product_name_key UNIQUE (name);

ALTER TABLE ONLY public.m_savings_product
    ADD CONSTRAINT m_savings_product_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_savings_product
    ADD CONSTRAINT m_savings_product_short_name_key UNIQUE (short_name);

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT m_staff_display_name_key UNIQUE (display_name);

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT m_staff_external_id_key UNIQUE (external_id);

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT m_staff_mobile_no_key UNIQUE (mobile_no);

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT m_staff_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_tax_group
    ADD CONSTRAINT m_tax_group_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT name UNIQUE (display_name, level_id);

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT uk_m_group_external_id UNIQUE (external_id, level_id);

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT uk_m_sat_external_id UNIQUE (external_id);

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT unique_reversal_external_id_loan_transaction UNIQUE (reversal_external_id);

ALTER TABLE ONLY public.m_appuser
    ADD CONSTRAINT username_org UNIQUE (username);

CREATE INDEX "FK1_m_client_gender_m_code_value" ON public.m_client USING btree (gender_cv_id);

CREATE INDEX "FK_approvedon_userid" ON public.m_loan USING btree (approvedon_userid);

CREATE INDEX "FK_closedon_userid" ON public.m_loan USING btree (closedon_userid);

CREATE INDEX "FK_disbursedon_userid" ON public.m_loan USING btree (disbursedon_userid);

CREATE INDEX "FK_glim_id" ON public.m_loan USING btree (glim_id);

CREATE INDEX "FK_group_id" ON public.glim_accounts USING btree (group_id);

CREATE INDEX "FK_gsim_group_id" ON public.gsim_accounts USING btree (group_id);

CREATE INDEX "FK_gsim_id" ON public.m_savings_account USING btree (gsim_id);

CREATE INDEX "FK_loan_expected_maturedon_date" ON public.m_loan USING btree (expected_maturedon_date);

CREATE INDEX "FK_loan_last_closed_business_date" ON public.m_loan USING btree (last_closed_business_date);

CREATE INDEX "FK_loan_ltp_strategy" ON public.m_loan USING btree (loan_transaction_strategy_id);

CREATE INDEX "FK_loan_overpaidon_date" ON public.m_loan USING btree (overpaidon_date);

CREATE INDEX "FK_loan_status_id" ON public.m_loan USING btree (loan_status_id);

CREATE INDEX "FK_ltp_strategy" ON public.m_product_loan USING btree (loan_transaction_strategy_id);

CREATE INDEX "FK_m_charge_acc_gl_account" ON public.m_charge USING btree (income_or_liability_account_id);

CREATE INDEX "FK_m_charge_m_tax_group" ON public.m_charge USING btree (tax_group_id);

CREATE INDEX "FK_m_client_classification_m_code_value" ON public.m_client USING btree (client_classification_cv_id);

CREATE INDEX "FK_m_client_m_code" ON public.m_client USING btree (closure_reason_cv_id);

CREATE INDEX "FK_m_client_m_image" ON public.m_client USING btree (image_id);

CREATE INDEX "FK_m_client_m_office" ON public.m_client USING btree (transfer_to_office_id);

CREATE INDEX "FK_m_client_m_savings_account" ON public.m_client USING btree (default_savings_account);

CREATE INDEX "FK_m_client_m_savings_product" ON public.m_client USING btree (default_savings_product);

CREATE INDEX "FK_m_client_substatus_m_code_value" ON public.m_client USING btree (sub_status);

CREATE INDEX "FK_m_client_type_m_code_value" ON public.m_client USING btree (client_type_cv_id);

CREATE INDEX "FK_m_client_type_m_code_value_withdraw" ON public.m_client USING btree (withdraw_reason_cv_id);

CREATE INDEX "FK_m_client_type_mcode_value_reject" ON public.m_client USING btree (reject_reason_cv_id);

CREATE INDEX "FK_m_group_level" ON public.m_group USING btree (level_id);

CREATE INDEX "FK_m_group_m_code" ON public.m_group USING btree (closure_reason_cv_id);

CREATE INDEX "FK_m_loan_m_staff" ON public.m_loan USING btree (loan_officer_id);

CREATE INDEX "FK_m_loan_transaction_m_office" ON public.m_loan_transaction USING btree (office_id);

CREATE INDEX "FK_m_loan_transaction_m_payment_detail" ON public.m_loan_transaction USING btree (payment_detail_id);

CREATE INDEX "FK_m_loanpurpose_codevalue" ON public.m_loan USING btree (loanpurpose_cv_id);

CREATE INDEX "FK_m_payment_detail_m_payment_type" ON public.m_payment_detail USING btree (payment_type_id);

CREATE INDEX "FK_m_payment_detail_m_payment_types" ON public.m_charge USING btree (payment_type_id);

CREATE INDEX "FK_m_savings_account_transaction_m_office" ON public.m_savings_account_transaction USING btree (office_id);

CREATE INDEX "FK_m_savings_account_transaction_m_payment_detail" ON public.m_savings_account_transaction USING btree (payment_detail_id);

CREATE INDEX "FK_m_staff_m_image" ON public.m_staff USING btree (image_id);

CREATE INDEX "FK_m_staff_m_office" ON public.m_staff USING btree (office_id);

CREATE INDEX "FK_mappings_m_loan_repayment_schedule" ON public.m_loan_transaction_repayment_schedule_mapping USING btree (loan_repayment_schedule_id);

CREATE INDEX "FK_mappings_m_loan_transaction" ON public.m_loan_transaction_repayment_schedule_mapping USING btree (loan_transaction_id);

CREATE INDEX "FK_rejectedon_userid" ON public.m_loan USING btree (rejectedon_userid);

CREATE INDEX "FK_savings_account_last_closed_business_date" ON public.m_savings_account USING btree (last_closed_business_date);

CREATE INDEX "FK_savings_account_tax_group" ON public.m_savings_account USING btree (tax_group_id);

CREATE INDEX "FK_savings_product_tax_group" ON public.m_savings_product USING btree (tax_group_id);

CREATE INDEX "FK_tax_group_createdby" ON public.m_tax_group USING btree (createdby_id);

CREATE INDEX "FK_tax_group_lastmodifiedby" ON public.m_tax_group USING btree (lastmodifiedby_id);

CREATE INDEX "FK_withdrawnon_userid" ON public.m_loan USING btree (withdrawnon_userid);

CREATE INDEX "FK_writeoffreason_m_loan_m_code_value" ON public.m_loan USING btree (writeoff_reason_cv_id);

CREATE INDEX "Parent_Id_reference" ON public.m_group USING btree (parent_id);

CREATE INDEX "Parent_levelId_reference" ON public.m_group_level USING btree (parent_id);

CREATE INDEX charge_id ON public.m_loan_charge USING btree (charge_id);

CREATE INDEX client_staff_id ON public.m_client USING btree (staff_id);

CREATE INDEX fk2291c477e2551dcc ON public.m_office USING btree (parent_id);

CREATE INDEX fk488b92aa40be0710 ON public.m_loan_repayment_schedule USING btree (loan_id);

CREATE INDEX fk7c885877240145 ON public.m_loan USING btree (fund_id);

CREATE INDEX fk_acc_0000000001 ON public.acc_gl_account USING btree (parent_id);

CREATE INDEX fk_m_appuser_002x ON public.m_appuser USING btree (staff_id);

CREATE INDEX fk_m_group_client_001_idx ON public.m_loan USING btree (group_id, client_id);

CREATE INDEX fka6a8a7d77240145 ON public.m_product_loan USING btree (fund_id);

CREATE INDEX fkb3d587ce0dd567a ON public.m_appuser USING btree (office_id);

CREATE INDEX fkb6f935d87179a0cb ON public.m_loan USING btree (client_id);

CREATE INDEX fkb6f935d8c8d4b434 ON public.m_loan USING btree (product_id);

CREATE INDEX fkce00cab3e0dd567a ON public.m_client USING btree (office_id);

CREATE INDEX fkcfcea42640be0710 ON public.m_loan_transaction USING btree (loan_id);

CREATE INDEX fkcfcea42640be071z ON public.m_code_value USING btree (code_id);

CREATE INDEX fkglacc000000002 ON public.acc_gl_account USING btree (tag_id);

CREATE INDEX fksa00000000000001 ON public.m_savings_account USING btree (client_id);

CREATE INDEX fksa00000000000002 ON public.m_savings_account USING btree (group_id);

CREATE INDEX fksa00000000000003 ON public.m_savings_account USING btree (product_id);

CREATE INDEX fksat0000000001 ON public.m_savings_account_transaction USING btree (savings_account_id);

CREATE INDEX group_id ON public.m_loan USING btree (group_id);

CREATE INDEX group_office_id ON public.m_group USING btree (office_id);

CREATE INDEX idx_m_payment_detail_check_number ON public.m_payment_detail USING btree (check_number);

CREATE INDEX idx_m_payment_detail_receipt_number ON public.m_payment_detail USING btree (receipt_number);

CREATE INDEX idx_m_payment_detail_routing_code ON public.m_payment_detail USING btree (routing_code);

CREATE INDEX ind_m_loan_delinquency_tag_history_liftedon_date ON public.m_loan_delinquency_tag_history USING btree (liftedon_date);

CREATE INDEX ind_m_loan_delinquency_tag_history_loan_id ON public.m_loan_delinquency_tag_history USING btree (loan_id);

CREATE INDEX last_time_password_updated ON public.m_appuser USING btree (last_time_password_updated);

CREATE INDEX m_loan_charge_ibfk_2 ON public.m_loan_charge USING btree (loan_id);

CREATE INDEX staff_id ON public.m_group USING btree (staff_id);

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK1_m_client_gender_m_code_value" FOREIGN KEY (gender_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_approvedon_userid" FOREIGN KEY (approvedon_userid) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_client_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_client_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_closedon_userid" FOREIGN KEY (closedon_userid) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_disbursedon_userid" FOREIGN KEY (disbursedon_userid) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_glim_id" FOREIGN KEY (glim_id) REFERENCES public.glim_accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.glim_accounts
    ADD CONSTRAINT "FK_group_id" FOREIGN KEY (group_id) REFERENCES public.m_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.gsim_accounts
    ADD CONSTRAINT "FK_gsim_group_id" FOREIGN KEY (group_id) REFERENCES public.m_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT "FK_gsim_id" FOREIGN KEY (gsim_id) REFERENCES public.gsim_accounts(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT "FK_loan_charge_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT "FK_loan_charge_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_loan_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_loan_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_repayment_schedule
    ADD CONSTRAINT "FK_loan_repayment_schedule_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_repayment_schedule
    ADD CONSTRAINT "FK_loan_repayment_schedule_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT "FK_loan_transaction_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT "FK_loan_transaction_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_charge
    ADD CONSTRAINT "FK_m_charge_acc_gl_account" FOREIGN KEY (income_or_liability_account_id) REFERENCES public.acc_gl_account(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_charge
    ADD CONSTRAINT "FK_m_charge_m_tax_group" FOREIGN KEY (tax_group_id) REFERENCES public.m_tax_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_classification_m_code_value" FOREIGN KEY (client_classification_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_code" FOREIGN KEY (closure_reason_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_image" FOREIGN KEY (image_id) REFERENCES public.m_image(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_office" FOREIGN KEY (transfer_to_office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_savings_account" FOREIGN KEY (default_savings_account) REFERENCES public.m_savings_account(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_savings_product" FOREIGN KEY (default_savings_product) REFERENCES public.m_savings_product(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_m_staff" FOREIGN KEY (staff_id) REFERENCES public.m_staff(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_substatus_m_code_value" FOREIGN KEY (sub_status) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_type_m_code_value" FOREIGN KEY (client_type_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_type_m_code_value_withdraw" FOREIGN KEY (withdraw_reason_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT "FK_m_client_type_mcode_value_reject" FOREIGN KEY (reject_reason_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_delinquency_bucket_mappings
    ADD CONSTRAINT "FK_m_delinquency_bucket_mapping" FOREIGN KEY (delinquency_bucket_id) REFERENCES public.m_delinquency_bucket(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_delinquency_bucket_mappings
    ADD CONSTRAINT "FK_m_delinquency_range_mapping" FOREIGN KEY (delinquency_range_id) REFERENCES public.m_delinquency_range(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_delinquency_tag_history
    ADD CONSTRAINT "FK_m_delinquency_tags_loan" FOREIGN KEY (loan_id) REFERENCES public.m_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_delinquency_tag_history
    ADD CONSTRAINT "FK_m_delinquency_tags_range" FOREIGN KEY (delinquency_range_id) REFERENCES public.m_delinquency_range(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT "FK_m_group_level" FOREIGN KEY (level_id) REFERENCES public.m_group_level(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT "FK_m_group_m_code" FOREIGN KEY (closure_reason_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT "FK_m_group_m_staff" FOREIGN KEY (staff_id) REFERENCES public.m_staff(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_m_loan_m_staff" FOREIGN KEY (loan_officer_id) REFERENCES public.m_staff(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT "FK_m_loan_transaction_m_office" FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT "FK_m_loan_transaction_m_payment_detail" FOREIGN KEY (payment_detail_id) REFERENCES public.m_payment_detail(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_m_loanpurpose_codevalue" FOREIGN KEY (loanpurpose_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_payment_detail
    ADD CONSTRAINT "FK_m_payment_detail_m_payment_type" FOREIGN KEY (payment_type_id) REFERENCES public.m_payment_type(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_charge
    ADD CONSTRAINT "FK_m_payment_detail_m_payment_types" FOREIGN KEY (payment_type_id) REFERENCES public.m_payment_type(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT "FK_m_product_loan_m_delinquency_bucket" FOREIGN KEY (delinquency_bucket_id) REFERENCES public.m_delinquency_bucket(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT "FK_m_savings_account_transaction_m_office" FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT "FK_m_savings_account_transaction_m_payment_detail" FOREIGN KEY (payment_detail_id) REFERENCES public.m_payment_detail(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT "FK_m_staff_m_image" FOREIGN KEY (image_id) REFERENCES public.m_image(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_staff
    ADD CONSTRAINT "FK_m_staff_m_office" FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction_repayment_schedule_mapping
    ADD CONSTRAINT "FK_mappings_m_loan_repayment_schedule" FOREIGN KEY (loan_repayment_schedule_id) REFERENCES public.m_loan_repayment_schedule(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction_repayment_schedule_mapping
    ADD CONSTRAINT "FK_mappings_m_loan_transaction" FOREIGN KEY (loan_transaction_id) REFERENCES public.m_loan_transaction(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_rejectedon_userid" FOREIGN KEY (rejectedon_userid) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT "FK_savings_account_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT "FK_savings_account_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT "FK_savings_account_tax_group" FOREIGN KEY (tax_group_id) REFERENCES public.m_tax_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT "FK_savings_account_transaction_created_by" FOREIGN KEY (created_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT "FK_savings_account_transaction_last_modified_by" FOREIGN KEY (last_modified_by) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_product
    ADD CONSTRAINT "FK_savings_product_tax_group" FOREIGN KEY (tax_group_id) REFERENCES public.m_tax_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_tax_group
    ADD CONSTRAINT "FK_tax_group_createdby" FOREIGN KEY (createdby_id) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_tax_group
    ADD CONSTRAINT "FK_tax_group_lastmodifiedby" FOREIGN KEY (lastmodifiedby_id) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_withdrawnon_userid" FOREIGN KEY (withdrawnon_userid) REFERENCES public.m_appuser(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT "FK_writeoffreason_m_loan_m_code_value" FOREIGN KEY (writeoff_reason_cv_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT "Parent_Id_reference" FOREIGN KEY (parent_id) REFERENCES public.m_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group_level
    ADD CONSTRAINT "Parent_levelId_reference" FOREIGN KEY (parent_id) REFERENCES public.m_group_level(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_office
    ADD CONSTRAINT fk2291c477e2551dcc FOREIGN KEY (parent_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_repayment_schedule
    ADD CONSTRAINT fk488b92aa40be0710 FOREIGN KEY (loan_id) REFERENCES public.m_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT fk7c885877240145 FOREIGN KEY (fund_id) REFERENCES public.m_fund(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.acc_gl_account
    ADD CONSTRAINT fk_acc_0000000001 FOREIGN KEY (parent_id) REFERENCES public.acc_gl_account(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_appuser
    ADD CONSTRAINT fk_m_appuser_002 FOREIGN KEY (staff_id) REFERENCES public.m_staff(id);

ALTER TABLE ONLY public.m_product_loan
    ADD CONSTRAINT fka6a8a7d77240145 FOREIGN KEY (fund_id) REFERENCES public.m_fund(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_appuser
    ADD CONSTRAINT fkb3d587ce0dd567a FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT fkb6f935d87179a0cb FOREIGN KEY (client_id) REFERENCES public.m_client(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT fkb6f935d8c8d4b434 FOREIGN KEY (product_id) REFERENCES public.m_product_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_client
    ADD CONSTRAINT fkce00cab3e0dd567a FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_transaction
    ADD CONSTRAINT fkcfcea42640be0710 FOREIGN KEY (loan_id) REFERENCES public.m_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_code_value
    ADD CONSTRAINT fkcfcea42640be071z FOREIGN KEY (code_id) REFERENCES public.m_code(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.acc_gl_account
    ADD CONSTRAINT fkglacc000000002 FOREIGN KEY (tag_id) REFERENCES public.m_code_value(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT fksa00000000000001 FOREIGN KEY (client_id) REFERENCES public.m_client(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT fksa00000000000002 FOREIGN KEY (group_id) REFERENCES public.m_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account
    ADD CONSTRAINT fksa00000000000003 FOREIGN KEY (product_id) REFERENCES public.m_savings_product(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_savings_account_transaction
    ADD CONSTRAINT fksat0000000001 FOREIGN KEY (savings_account_id) REFERENCES public.m_savings_account(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_group
    ADD CONSTRAINT m_group_ibfk_1 FOREIGN KEY (office_id) REFERENCES public.m_office(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_arrears_aging
    ADD CONSTRAINT m_loan_arrears_aging_ibfk_1 FOREIGN KEY (loan_id) REFERENCES public.m_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT m_loan_charge_ibfk_1 FOREIGN KEY (charge_id) REFERENCES public.m_charge(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan_charge
    ADD CONSTRAINT m_loan_charge_ibfk_2 FOREIGN KEY (loan_id) REFERENCES public.m_loan(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

ALTER TABLE ONLY public.m_loan
    ADD CONSTRAINT m_loan_ibfk_1 FOREIGN KEY (group_id) REFERENCES public.m_group(id) ON UPDATE RESTRICT ON DELETE RESTRICT;

